version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres_db:5432/my_db
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env

  postgres_db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=my_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # For development only
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_config worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge