version: "3"

services:
    postgres:
        image: bitnami/postgresql:latest
        environment:
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=footy
        ports:
            - "5434:5432"

    redis:
        image: bitnami/redis:7.0
        environment:
            - REDIS_PASSWORD=password
            - REDIS_USER=redis
        ports:
            - "6377:6379"
